### ISSUE TITLE
Embed libvlc and libvlccore into exe

### ISSUE THREAD

**Issue by Junkern** [higankanshi/xZune.Vlc#44]
I am trying to have an exe where the libvlc is included as an embedded resource, so I do not have to copy around a bunch of files all the time, only the .exe
Can I follow this approach http://stackoverflow.com/questions/96732/embedding-one-dll-inside-another-as-an-embedded-resource-and-then-calling-it-fro and place the code to load the embedded assembly in ```xZune.Vlc.Wpf.VlcPlayer.cs```?

**Comment by higankanshi** [comment]
Ummmm...I'm afraid you can't do that.
Assembly.Load() is used for managed assembly.
But libvlc and libvlccore is unmanaged assembly.

**Comment by Junkern** [comment]
I already thought so :\ do you think that would work? https://github.com/Fody/Costura#unmanaged32assemblies--unmanaged64assemblies

**Comment by birbilis** [comment]
If you use dynamic instead of static importing of external methods you could do it. Not sure if the compiler can do it automatically now but in the past in c++ or delphi you had to do the loading of each exported proc from the dll and assignment to procedure pointers manually if you wanted dynamic loading (eg to not fail loading the app exe if dll was missing)

**Comment by birbilis** [comment]
Btw, now that I think of it, since one can set vlc libs path there is dynamic linking to the dlls instead of static one already (not sure if static is even possible with just c# and no c++ part).

So, you could embed the native dlls in your exe as resources (maybe vs allows you to add .dll to project and mark it as embedded resource else rename them to jpg or something to embed) and write them to a unique subfolder in temp at start, then point to there. 

.net has api to give you unique temp folder ( it creates the folder for you to make sure no other code grabbed that foldername)

**Comment by bamf43** [comment]
Hi, is there still a way to do it now ?

**Comment by birbilis** [comment]
@junkern
Not sure if meta.vlc uses a mixed-mode assembly, probably just uses a native one via interop directly

Mixed-mode ones contain managed and non-managed code in single DLL as it seems:
https://stackoverflow.com/questions/7266936/what-is-a-mixed-mode-assembly

Obviously mixed-mode ones could link to other native ones

Costura Fody supports mixed-mode, but native DLLs too:
Native Libraries and PreloadOrderNative libraries can be loaded by Costura automatically. To include a native library include it in your project as an Embedded Resource in a folder called costura32 or costura64 depending on the bittyness of the library.Optionally you can also specify the order that preloaded libraries are loaded. When using temporary assemblies from disk mixed mode assemblies are also preloaded.To specify the order of preloaded assemblies add a PreloadOrder element to the config.
<Costura>  
<PreloadOrder>    Foo    Bar  </PreloadOrder>
</Costura>

Or as an attribute with items delimited by a pipe |.
<Costura PreloadOrder='Foo|Bar' />
